In [2]:
import os
import pyreadr as pyr
import pandas as pd
import numpy as np
import plotly.express as px
from pathlib import Path

### Introducción a Python

In [3]:
nombre = 'Juan Camilo'
num = 3
decimal =2.15
condicion = True

In [4]:
### Imprimir el tipo de una variable
print(type(nombre))

<class 'str'>

In [5]:
print('Hello World!')

Hello World!

In [6]:
print(f'Mi nombre es {nombre}')

Mi nombre es Juan Camilo

In [7]:
print(f'La variable num es {num}')

La variable num es 3

In [8]:
print(f'La variable num es {condicion}')

La variable num es True

### Introducción a las listas

In [9]:
beatles = ['John', 'Paul', 'George', 'Ringo']
print(beatles)
print(type(beatles))

['John', 'Paul', 'George', 'Ringo']
<class 'list'>

In [10]:
notas_taller = [4.2, 3.8, 4.5, 2, 5]
print(notas_taller)

[4.2, 3.8, 4.5, 2, 5]

In [11]:
random_list = ['mytext', 3.0, 7, [10, 20]]
print(random_list)

['mytext', 3.0, 7, [10, 20]]

In [12]:
notas_taller.append(5)
print(notas_taller)

[4.2, 3.8, 4.5, 2, 5, 5]

In [13]:
### Acceder al primer elemento de la lista
beatles[0]

'John'

In [14]:
### Tamaño de la lista
len(beatles)

4

### Diccionarios como estructuras de datos en Python

In [15]:
diccionario = {'nombre':'Fabián', 
               'semestre':'3', 
               'carrera':'economía', 
               'maestría':True}

In [16]:
diccionario['nombre']

'Fabián'

In [17]:
'nombre' in diccionario

True

In [18]:
diccionario.keys()

dict_keys(['nombre', 'semestre', 'carrera', 'maestría'])

In [19]:
diccionario['carrera'] = 'Estadística'

In [20]:
diccionario

{'nombre': 'Fabián',
 'semestre': '3',
 'carrera': 'Estadística',
 'maestría': True}

### Introducción a los condicionales

In [21]:
lado_oscuro = 'Anakin Skywalker'
hijo = 'Luke Skywalker'

In [22]:
if lado_oscuro == 'Anakin Skywalker':
    print('Darth Vader')

if lado_oscuro == hijo:
    print('Luke, no te rindas al odio. Eso lleva al lado oscuro')

Darth Vader

In [23]:
if lado_oscuro == 'hijo':
    print('Luke, no te rindas al odio. Eso lleva al lado oscuro')
else:
    print(lado_oscuro + 'es el padre de' + hijo)

Anakin Skywalkeres el padre deLuke Skywalker

### Introducción a los bucles

In [24]:
for i in range(0, 5):
    print(i)

0
1
2
3
4

In [25]:
for i in range(3, 8, 2):
    print(i)

3
5
7

In [26]:
for i in 'Python':
    print(i)

P
y
t
h
o
n

In [27]:
mago = ["Harry", "Hermione", "Ron", "Voldemort", "Dumbledore"]

for i in mago:
    if i == 'Voldemort':
        break
    print(i)

Harry
Hermione
Ron

In [28]:
def suma_dos_numeros(a, b):
    """
    Esta función toma dos números y entrega la suma de estos.

    Parameters:
        a (float): número a sumar.
        b (float): número a sumar.

    Returns:
        resultado (float): suma de a + b
    """
    resultado = a + b

    return(resultado)

In [29]:
suma_dos_numeros(1, 2)

3

### Introducción a Pandas

In [30]:
df = pd.read_csv('../data/adult.csv')
df = df.drop(columns = ['Unnamed: 0'])
df.head(5)

,age,workclass,fnlwgt,education,education num,marital status,occupation,relationship,race,sex,capital gain,capital loss,hours per week,native country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [31]:
df.tail(5)

,age,workclass,fnlwgt,education,education num,marital status,occupation,relationship,race,sex,capital gain,capital loss,hours per week,native country,income
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  str
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  str
 4   education num   32561 non-null  int64
 5   marital status  32561 non-null  str
 6   occupation      32561 non-null  str
 7   relationship    32561 non-null  str
 8   race            32561 non-null  str
 9   sex             32561 non-null  str
 10  capital gain    32561 non-null  int64
 11  capital loss    32561 non-null  int64
 12  hours per week  32561 non-null  int64
 13  native country  32561 non-null  str
 14  income          32561 non-null  str
dtypes: int64(6), str(9)
memory usage: 3.7 MB

In [33]:
df.describe()

,age,fnlwgt,education num,capital gain,capital loss,hours per week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [34]:
### Renombrando las columnas
df.rename(columns = {'education num':'education_num',
                   'marital status':'marital_tatus',
                   'capital gain': 'capital_gain',
                   'capital loss': 'capital_loss',
                   'hours per week': 'hours_per_week',
                   'native country': 'native_country'}, 
                   inplace = True)

### Usando iloc

In [35]:
### En el siguiente ejemplo se ubican las filas desde la 10 hasta la 20 y las dos primera columnas

df.iloc[10:21, :2]

    age         workclass
10   37           Private
11   30         State-gov
12   23           Private
13   32           Private
14   40           Private
15   34           Private
16   25  Self-emp-not-inc
17   32           Private
18   38           Private
19   43  Self-emp-not-inc
20   40           Private

### Usando loc

In [36]:
### Localizar filas de acuerdo a una condición
### Obtener las filas en las que los años de educación sean iguales a 16

df.loc[df['education_num'] == 16]

,age,workclass,fnlwgt,education,education_num,marital_tatus,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
63,42,Private,116632,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,45,United-States,>50K
89,43,Federal-gov,410867,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,50,United-States,>50K
96,48,Self-emp-not-inc,191277,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,1902,60,United-States,>50K
189,58,State-gov,109567,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,1,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32429,51,Local-gov,203334,Doctorate,16,Divorced,Exec-managerial,Not-in-family,White,Female,0,0,45,United-States,>50K
32469,58,Self-emp-inc,181974,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,99,?,<=50K
32470,50,Private,485710,Doctorate,16,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,50,United-States,<=50K
32532,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K

In [37]:
#Ejercicio: Encontrar las personas cuyo trabajo por horas sea igual o mayor a 45
df.loc[df['hours_per_week'] >= 45]

,age,workclass,fnlwgt,education,education_num,marital_tatus,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32538,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32543,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K

In [38]:
### Cambiar los valores de '?' por NaNs de Pandas
df = df.replace('?', pd.NA)

In [39]:
df.select_dtypes(include = 'number').corr()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
age,1.000000,-0.076646,0.036527,0.077674,0.057775,0.068756
fnlwgt,-0.076646,1.000000,-0.043195,0.000432,-0.010252,-0.018768
education_num,0.036527,-0.043195,1.000000,0.122630,0.079923,0.148123
capital_gain,0.077674,0.000432,0.122630,1.000000,-0.031615,0.078409
capital_loss,0.057775,-0.010252,0.079923,-0.031615,1.000000,0.054256
hours_per_week,0.068756,-0.018768,0.148123,0.078409,0.054256,1.000000

In [40]:
### Personas cuyo workclass es 'Private'
### o que su income sea '>50k'
### y a su ves tengan education_num mayor a 10.

In [41]:
df.loc[df['workclass'] == 'Private']

,age,workclass,fnlwgt,education,education_num,marital_tatus,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [42]:
df['income'].value_counts()

income
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [43]:
df.loc[((df['workclass'] == 'Private') | (df['income'] == '>50K')) & (df['education_num'] > 10)]

,age,workclass,fnlwgt,education,education_num,marital_tatus,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32546,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K

### Ordenar valores ascendentes o descendentes

In [44]:
df.sort_values(['age', 'hours_per_week'], ascending = [0, 1]).head(10)

,age,workclass,fnlwgt,education,education_num,marital_tatus,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
11731,90,NaN,39824,HS-grad,9,Widowed,NaN,Not-in-family,White,Male,401,0,4,United-States,<=50K
4109,90,NaN,256514,Bachelors,13,Widowed,NaN,Other-relative,White,Female,991,0,10,United-States,<=50K
12451,90,NaN,225063,Some-college,10,Never-married,NaN,Own-child,Asian-Pac-Islander,Male,0,0,10,South,<=50K
18413,90,Private,313749,Bachelors,13,Never-married,Prof-specialty,Own-child,White,Female,0,0,10,United-States,<=50K
24043,90,Self-emp-not-inc,82628,HS-grad,9,Never-married,Exec-managerial,Not-in-family,White,Male,2964,0,12,United-States,<=50K
8973,90,Private,46786,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,9386,0,15,United-States,>50K
25303,90,NaN,175444,7th-8th,4,Separated,NaN,Not-in-family,White,Female,0,0,15,United-States,<=50K
14159,90,Local-gov,187749,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Husband,Asian-Pac-Islander,Male,0,0,20,Philippines,<=50K
18277,90,Private,311184,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0,0,20,NaN,<=50K
11512,90,Private,87285,HS-grad,9,Never-married,Other-service,Own-child,White,Female,0,0,24,United-States,<=50K

In [45]:
### Catidad de elementos nulos en el dataframe
df.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_tatus        0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

In [46]:
droping_nan = df.dropna(inplace = False, axis = 0)

In [47]:
droping_nan.head(10)

,age,workclass,fnlwgt,education,education_num,marital_tatus,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K

In [48]:
len(droping_nan)

30162

In [49]:
droping_nan.reset_index(drop = True, inplace = True)

In [51]:
### Relleno de los valores nulos con fillna
df.fillna(value = {'workclass':'Private'}, inplace = True)

,age,workclass,fnlwgt,education,education_num,marital_tatus,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [52]:
df.drop(columns = ['native_country'], inplace = True)

In [54]:
df.select_dtypes(include = 'number').groupby(df['workclass']).mean()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
workclass,,,,,,
Federal-gov,42.590625,185221.243750,10.973958,833.232292,112.268750,41.379167
Local-gov,41.751075,188639.712852,11.042045,880.202580,109.854276,40.982800
Never-worked,20.571429,225989.571429,7.428571,0.000000,0.000000,28.428571
Private,37.109123,192446.206791,9.833361,868.081037,78.568156,39.642345
Self-emp-inc,46.017025,175981.344086,11.137097,4875.693548,155.138889,48.818100
Self-emp-not-inc,44.969697,175608.641480,10.226289,1886.061787,116.631641,44.421881
State-gov,39.436055,184136.613251,11.375963,701.699538,83.256549,39.031587
Without-pay,47.785714,174267.500000,9.071429,487.857143,0.000000,32.714286

In [60]:
df.groupby(['workclass'])[['age', 'education_num']].agg(['mean', 'sum'])

                        age         education_num
                       mean     sum          mean     sum
workclass
Federal-gov       42.590625   40887     10.973958   10535
Local-gov         41.751075   87385     11.042045   23111
Never-worked      20.571429     144      7.428571      52
Private           37.109123  910361      9.833361  241232
Self-emp-inc      46.017025   51355     11.137097   12429
Self-emp-not-inc  44.969697  114268     10.226289   25985
State-gov         39.436055   51188     11.375963   14766
Without-pay       47.785714     669      9.071429     127

In [61]:
df[['workclass', 'age']].value_counts()

workclass     age
Private       23     779
              25     725
              28     708
              31     703
              20     696
                    ...
Federal-gov   90       1
Without-pay   68       1
              67       1
Private       87       1
Never-worked  30       1
Name: count, Length: 412, dtype: int64

In [62]:
df.loc[df['workclass'].str.contains('gov')].head

<bound method NDFrame.head of        age    workclass  fnlwgt     education  education_num  \
0       39    State-gov   77516     Bachelors             13
11      30    State-gov  141297     Bachelors             13
22      35  Federal-gov   76845           9th              5
25      56    Local-gov  216851     Bachelors             13
30      23    Local-gov  190709    Assoc-acdm             12
...    ...          ...     ...           ...            ...
32518   57    Local-gov  110417       HS-grad              9
32540   45    State-gov  252208       HS-grad              9
32543   45    Local-gov  119199    Assoc-acdm             12
32545   39    Local-gov  111499    Assoc-acdm             12
32549   43    State-gov  255835  Some-college             10

            marital_tatus       occupation    relationship  \
0           Never-married     Adm-clerical   Not-in-family
11     Married-civ-spouse   Prof-specialty         Husband
22     Married-civ-spouse  Farming-fishing         Husband
25     Married-civ-spouse     Tech-support         Husband
30          Never-married  Protective-serv   Not-in-family
...                   ...              ...             ...
32518  Married-civ-spouse     Craft-repair         Husband
32540           Separated     Adm-clerical       Own-child
32543            Divorced   Prof-specialty       Unmarried
32545  Married-civ-spouse     Adm-clerical            Wife
32549            Divorced     Adm-clerical  Other-relative

                     race     sex  capital_gain  capital_loss  hours_per_week  \
0                   White    Male          2174             0              40
11     Asian-Pac-Islander    Male             0             0              40
22                  Black    Male             0             0              40
25                  White    Male             0             0              40
30                  White    Male             0             0              52
...                   ...     ...           ...           ...             ...
32518               White    Male         99999             0              40
32540               White  Female             0             0              40
32543               White  Female             0             0              48
32545               White  Female             0             0              20
32549               White  Female             0             0              40

      income
0      <=50K
11      >50K
22     <=50K
25      >50K
30     <=50K
...      ...
32518   >50K
32540  <=50K
32543  <=50K
32545   >50K
32549  <=50K

[4351 rows x 14 columns]>

### Creando una función

In [63]:
def grupo_edad(age):
    if age < 25:
        return 'Young'
    elif age < 45:
        return 'Young adult'
    elif age <65:
        return 'Adult'
    else: 
        return 'Senior citizen'

In [64]:
df['age_group'] = df['age'].apply(grupo_edad)
df[['age', 'age_group']].head()

   age    age_group
0   39  Young adult
1   50        Adult
2   38  Young adult
3   53        Adult
4   28  Young adult